import { Inter, Poppins, Raleway, Montserrat, Playfair_Display } from "next/font/google";
import "./globals.css";
import Header from "@/components/molecules/Header/Header";
import TopNav from "@/components/molecules/TopNav/TopNav";
import Footer from "@/components/molecules/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-poppins',
})

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-raleway',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-montserrat',
})

const playfairDisplay = Playfair_Display({
  weight: ['400', '500', '700'], // Specify weights
  subsets: ['latin'],
  variable: '--font-playfair', // Define a custom property for Tailwind
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${raleway.variable} ${inter.className} ${montserrat.variable} ${playfairDisplay.variable} font-sans`}>
        <TopNav />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
